config/routes.rb
QualityKeeper::Application.routes.draw do
  resources :projects

  root :to => "home#index"

end

app/models/project.rb
class Project < ActiveRecord::Base
end

app/controllers/application_controller.rb
require 'subdomain'

class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :check_for_mobile

  def check_for_mobile
    request.format = :mobile if Subdomain.is_mobile_subdomain?(request.subdomain)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @projects }
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @project = Project.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/new
  # GET /projects/new.json
  def new
    @project = Project.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @project }
    end
  end

  # GET /projects/1/edit
  def edit
    @project = Project.find(params[:id])
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(params[:project])

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render json: @project, status: :created, location: @project }
      else
        format.html { render action: "new" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /projects/1
  # PUT /projects/1.json
  def update
    @project = Project.find(params[:id])

    respond_to do |format|
      if @project.update_attributes(params[:project])
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def generate_current_class(controller_name)
    css_class = ''
    if controller.controller_name.casecmp(controller_name) == 0
      css_class = 'class="current"'
    end
    css_class
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/home/index.mobile.erb
<h1>Home</h1>
<% images = ['bar-chart','addressbook','configuration','processing','star'] %>
<% colors = ['green','white'] %>

<% images.length.times.with_index do |index| %>
<div style="clear:both; margin-bottom:5px;">
<% images.each_with_index do |image, index2| %>
<% color = colors[1] if index != index2 %>
<% color = colors[0] if index == index2 %>

<% additional = "" %>
<% additional = "selected" if index == index2 %>
<div class="<%= color %>-<%=image %> sprite status_bar <%= additional %>">&nbsp;</div>
<% end %>
<div style="height: 10px;clear:both;" />
</div>
<% end %>

app/views/layouts/application.html.erb
<!doctype html>
<!--[if lt IE 7 ]> <html class="no-js ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="no-js ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="no-js ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title><%= t('application.title') %></title>

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

  <meta name="description" content="<%= t('application.description') %>">
  <meta name="author" content="David Rouchy">

  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <div id="container">
        <header id="top">
            <%= render 'shared/header' %>
        </header>

        <div id="main" role="main">
            <%= yield %>
        </div>

        <footer>
            <%= render 'shared/footer' %>
        </footer>
    </div>
</body>
</html>

app/views/layouts/application.mobile.erb
<!doctype html>
<!-- Conditional comment for mobile ie7 http://blogs.msdn.com/b/iemobile/ -->
<!-- Appcache Facts http://appcachefacts.info/ -->
<!--[if IEMobile 7 ]>    <html class="no-js iem7" manifest="default.appcache?v=1"> <![endif]-->
<!--[if (gt IEMobile 7)|!(IEMobile)]><!--> <html class="no-js" manifest="default.appcache"> <!--<![endif]-->

<head>
  <meta charset="utf-8">

  <title><%= t('application.title') %></title>

  <meta name="description" content="<%= t('application.description') %>">
  <meta name="author" content="David Rouchy">
  
  <!-- Mobile viewport optimization http://goo.gl/b9SaQ -->
  <meta name="HandheldFriendly" content="True">
  <meta name="MobileOptimized" content="320"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <!-- Home screen icon  Mathias Bynens http://goo.gl/6nVq0 -->
  <!-- For iPhone 4 with high-resolution Retina display: -->
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="img/h/apple-touch-icon.png">
  <!-- For first-generation iPad: -->
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="img/m/apple-touch-icon.png">
  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <link rel="apple-touch-icon-precomposed" href="img/l/apple-touch-icon-precomposed.png">
  <!-- For nokia devices: -->
  <link rel="shortcut icon" href="img/l/apple-touch-icon.png">
  
  <!--iOS web app, deletable if not needed -->
  <!--<meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <link rel="apple-touch-startup-image" href="img/l/splash.png">-->
  
  <!-- Mobile IE allows us to activate ClearType technology for smoothing fonts for easy reading -->
  <meta http-equiv="cleartype" content="on">
	
  
  <%= stylesheet_link_tag    "mobile" %>
  <%= javascript_include_tag "mobile" %>
 
</head>

<body>

  <div id="container">
    <header>

    </header>
    <div id="main" role="main">
      <%= yield %>
    </div>
    
    <footer>

    </footer>
  </div> <!--! end of #container -->
  
  <script>
    // iPhone Scale Bug Fix, read this when using http://www.blog.highub.com/mobile-2/a-fix-for-iphone-viewport-scale-bug/
    MBP.scaleFix();
  
  <!-- Debugger - remove for production -->
  <!-- <script src="https://getfirebug.com/firebug-lite.js"></script> -->
  
  <!-- mathiasbynens.be/notes/async-analytics-snippet Change UA-XXXXX-X to be your site's ID -->
  <!--script>
    var _gaq=[["_setAccount","UA-XXXXX-X"],["_trackPageview"]];
    (function(d,t){var g=d.createElement(t),s=d.getElementsByTagName(t)[0];g.async=1;
    g.src=("https:"==location.protocol?"//ssl":"//www")+".google-analytics.com/ga.js";
    s.parentNode.insertBefore(g,s)}(document,"script"));
  </script-->

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :logo %><br />
    <%= f.text_field :logo %>
  </div>
  <div class="field">
    <%= f.label :git_url %><br />
    <%= f.text_field :git_url %>
  </div>
  <div class="field">
    <%= f.label :git_login %><br />
    <%= f.text_field :git_login %>
  </div>
  <div class="field">
    <%= f.label :git_password %><br />
    <%= f.text_field :git_password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<ul id="projects">
    <% @projects.each do |project| %>
        <li class="project">
            <h2><%= image_tag project.logo, :alt => project.name,  :width => 30 %><%= project.name %></h2>
            
            <div class="description"><%= project.description%></div>
            <div class="controls">
                <%= link_to t('projects.show_link_name'), project_path(project) %>
                <%= link_to t('projects.edit_link_name'), edit_project_path(project) %>
                <%= link_to t('projects.delete_link_name'), project_path(project), confirm: 'Are you sure?', method: :delete %>
            </div>
        </li>
    <% end %>
</ul>

<br />

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div id="project_information">
  <header>
    <%= image_tag @project.logo, :width => 30, :alt => @project.name%><h1><%= @project.name %></h1>
  </header>
  <p class="description"><%= @project.description %></p>
  <p class="url"><%= @project.git_url %></p>
</div>

<div id="commit">
    foo
</div>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/shared/_footer.html.erb
my footer!

app/views/shared/_header.html.erb
<%= image_tag 'small_logo.png', :alt => t('application.title'), :id => 'logo' %>

<nav id="top_bar">
    <ul>
        <li <%= raw generate_current_class('home') %>><a href="/"><%= t('home.link_name') %></a></li>
        <li <%= raw generate_current_class('projects') %>><a href="<%= projects_path %>"><%= t('projects.link_name') %></a></li>
        <li <%= raw generate_current_class('stats') %>><a href="#"><%= t('stats.link_name') %></a></li>
        <li <%= raw generate_current_class('about') %>><a href="#"><%= t('about.link_name') %></a></li>
        <li <%= raw generate_current_class('user') %>><a href="#"><%= t('user.link_name') %></a></li>
    </ul>
</nav>